### ISSUE TITLE
Adjustment for incorrect card types

### ISSUE THREAD

**Issue by Tim-Prince** [ericjorgensen/magic-card-fetcher#2]
If you can incorporate  information about individual card selections, then add:

• If the initial random selection has a card type that is anything other than “Legendary Creature” or “Legendary Planeswalker” that also includes “[Planeswalker’s name] can be your commander” in its oracle text,  reselect.

**Comment by ericjorgensen** [comment]
@Tim-Prince are there any criteria within the Advanced Search (https://scryfall.com/advanced) that can be used to achieve this effect?

In other words, is there a way to get the search results we want without having to add the logic you described to the app? I'm looking at the "Criteria" dropdown, for example: 

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1682088/175952027-71f57e47-de93-4788-aa50-c71c0a461f51.png">

**Comment by Tim-Prince** [comment]
@ericjorgensen, you should be able to do that under the “Type Line” dropdown.  Notice that you need both legendary and the other card type together to get the results we want. 

![BC89F62A-A951-4EAE-B276-F32B3C2A18EF](https://user-images.githubusercontent.com/105868257/176032125-047c0ad8-e58c-4f48-9e23-165ef51eac5e.jpeg)

**Comment by ericjorgensen** [comment]
Should be fixed with https://github.com/ericjorgensen/magic-card-fetcher/commit/1a4c44ed3334f6120afda514a203c0c16171346e
